apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cron
spec: 
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec:
      template:
        spec:
          containers:
            - name: data-cleanup
              image: linuxacademy/data-cleanup:1
          restartPolicy: OnFailure              