apiVersion: v1
kind: Pod
metadata:
  name: mypodissecure

spec:
  securityContext:
    runAsUser: 2001
    fsGroup: 3001
  containers:
    - name: mypodissecure
      image: busybee
      command: ['sh', '-c', 'cat /message/messate.txt && sleep 3600']
      volumeMount:
        name: localvol
        mountPath: /message
  volumes:
    name: localvol
    hostPath: 
      path: /etc/message      