apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: candy2-deployment
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: candy2-ws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: candy2-ws
    spec:
      containers:
      - image: linuxacademycontent/candy-service:2
        imagePullPolicy: IfNotPresent
        name: candy2-ws
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30