apiVersion: v1
kind: Pod
metadata:
  name: mycandyservicepod
spec:
  serviceAccountName: candy-svc
  securityContext:
    fsGroup: 2000
  containers:
    - name: candypod
      image: linuxacademycontent/candy-service:1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-password
            key: dbpass
      volumeMounts:
      - name: candyconfig
        mountPath: /etc/candy-service
  volumes:
    - name: candyconfig
      configMap:
        name: candy-service-config
        items:
         - key: "candy.cfg"
           path: "candy.cfg"